UtakoSite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.flatpages import views
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movie.urls')),
    path('auth/', include('register.urls')),
    path('mypage/', include('mypage.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('player/', views.flatpage, {'url': 'player/'}),
    re_path('^$', views.flatpage, {'url': 'index/'}),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path('^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

api/urls.py
from django.urls import path, include
from rest_framework import routers, serializers, viewsets
from .views import StatusList, StatusRetrieve, MapRangeList, MapPointList, PlayerList, SettingsRetrieve
from rest_framework import routers

urlpatterns = [
    path('movie/', StatusList.as_view()),
    path('movie/<str:pk>/', StatusRetrieve.as_view(), name='detail'),
    path('vocalosphere/range/', MapRangeList.as_view()),
    path('vocalosphere/point/', MapPointList.as_view()),
    path('player/', PlayerList.as_view()),
    path('settings/', SettingsRetrieve.as_view()),
]

register/urls.py
from django.urls import path, include

from . import views

app_name = 'register'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.Registration.as_view(), name='register'),
    path('activate/', views.Activation.as_view(), name='activate'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

register/models.py
from django.db import models

# Create your models here.

register/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordResetForm,
    PasswordChangeForm,
    SetPasswordForm,
)
from django_registration.forms import RegistrationFormUniqueEmail

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class ResetPasswordForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class ResetPasswordConfirmForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class ChangePasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class UtakoRegistrationForm(RegistrationFormUniqueEmail):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

register/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from django.views import generic
from django_registration.backends.activation.views import RegistrationView, ActivationView
from django.urls import reverse_lazy

from .forms import (
    LoginForm,
    ResetPasswordForm,
    UtakoRegistrationForm,
    ResetPasswordConfirmForm,
    ChangePasswordForm,
)

class Login(LoginView):
    form_class = LoginForm
    template_name = 'register/login.html'

class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'register/logout.html'

class PasswordReset(PasswordResetView):
    form_class = ResetPasswordForm
    template_name = 'register/password_reset.html'
    email_template_name = 'register/password_reset_email.html'
    subject_template_name = 'register/password_reset_subject.html'
    success_url = reverse_lazy( 'register:password_reset_done' )

class PasswordResetDone(PasswordResetDoneView):
    template_name = 'register/password_reset_done.html'

class PasswordResetConfirm(PasswordResetConfirmView):
    form_class = ResetPasswordConfirmForm
    template_name = 'register/password_reset_confirm.html'
    success_url = reverse_lazy('register:password_reset_complete')

class PasswordResetComplete(PasswordResetCompleteView):
    template_name = 'register/password_reset_complete.html'

class PasswordChange(PasswordChangeView):
    form_class = ChangePasswordForm
    template_name = 'register/password_change.html'
    success_url = reverse_lazy( 'register:password_change_done' )

class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'register/password_change_done.html'

class Registration(RegistrationView):
    form_class = UtakoRegistrationForm
    template_name = 'register/register.html'
    email_body_template = 'register/activation_email.txt'
    email_subject_template = 'register/activation_email_subject.txt'
    disallowed_url = reverse_lazy('register:register')
    success_url = reverse_lazy('register:login')

class Activation(ActivationView):
    template_name = 'register/activation_failed.html'
    success_url = reverse_lazy('register:login')
    def activate(self, request, *args, **kwargs):
        return super().activate(request, activation_key = request.GET.get('activation_key'))

register/templates/register/activation_failed.html
{% extends "appbase.html" %}

{% block title %}
  LOGIN
{% endblock %}

{% block content %}
<div class="row">
  <div class="card my-5 col-lg-6 offset-lg-3">
    <div class="card-body">
      <div class="alert alert-danger" role="alert">
        アクティベーションできませんでした。
        {{activation_error}}
      </div>
    </div>
  </div>
</div>

{% endblock %}

register/templates/register/login.html
{% extends "appbase.html" %}

{% block title %}
  LOGIN
{% endblock %}

{% block content %}
<div class="row">
  <div class="card my-5 col-lg-6 offset-lg-3">
    <div class="card-body">
      {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {% for _, err_state in form.errors.items %}
            {{err_state}}
          {% endfor %}
        </div>
      {% endif %}
      {% if next %}
        <div class="alert alert-danger" role="alert">
          {% if user.is_authenticated %}
          <p>このページへのアクセス権限が足りません．このページへのアクセス権を所有する
          アカウントでログインしてください．</p>
          {% else %}
          <p>この機能を利用するためにはログインが必要です．</p>
          {% endif %}
        </div>
      {% endif %}

      <div class="my-2">
        <form method="post" action="{% url 'register:login' %}">
          {% csrf_token %}
          <div class="form-group">
            {{form.username.label_tag}}
            {{form.username}}
          </div>
          <div class="form-group">
            {{form.password.label_tag}}
            {{form.password}}
          </div>
          <input type="submit" class="btn btn-primary float-right my-2" value="ログイン" />
          <input type="hidden" name="next" value="{{ next }}" />
          <a href="{% url "register:password_reset" %}">パスワードを忘れました</a>
        </form>
      </div>
      <a href="{% url "social:begin" "google-oauth2" %}"><div class="btn btn-primary col-12 my-2">Googleでログイン</div></a>
      <a href="{% url "social:begin" "twitter" %}"><div class="btn btn-primary col-12 my-2">Twitterでログイン</div></a>
      <hr>
      <a href="{% url "register:register" %}"><div class="btn btn-primary col-12 my-2">新規登録</div></a>
    </div>
  </div>
</div>

{% endblock %}

register/templates/register/logout.html
{% extends "appbase.html" %}

{% block title %}
  LOGOUT
{% endblock %}

{% block content %}
<div class="row">
  <div class="card my-5 col-lg-6 offset-lg-3">
    <div class="card-body">
      ログアウトが完了しました．
    </div>
  </div>
</div>

{% endblock %}

register/templates/register/password_change.html
{% extends "appbase.html" %}

{% block title %}
パスワードの変更
{% endblock %}

{% block content %}
<div class="row">
  <div class="card my-5 col-lg-6 offset-lg-3">
    <div class="card-body">
      {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {% for _, err_state in form.errors.items %}
            {{err_state}}
          {% endfor %}
        </div>
      {% endif %}

      <form method="post" action="{% url 'register:password_change' %}" >
        {% csrf_token %}
        <div class="form-group">
          {{form.old_password.label_tag}}
          {{form.old_password}}
        </div>
        <div class="form-group">
          {{form.new_password1.label_tag}}
          {{form.new_password1}}
        </div>
        <div class="form-group">
          {{form.new_password2.label_tag}}
          {{form.new_password2}}
        </div>
        <input type="submit" class="btn btn-primary float-right" value="パスワードを変更" />
        <input type="hidden" name="next" value="{{ next }}" />
      </form>
    </div>
  </div>
</div>

{% endblock %}

register/templates/register/password_change_done.html
{% extends "appbase.html" %}

{% block title %}
パスワードの変更
{% endblock %}

{% block content %}
<div class="row">
  <div class="card my-5 col-lg-6 offset-lg-3">
    <div class="card-body">
      パスワードの変更が完了しました。
    </div>
  </div>
</div>

{% endblock %}

register/templates/register/password_reset.html
{% extends "appbase.html" %}

{% block title %}
パスワードのリセット
{% endblock %}

{% block content %}
<div class="row">
  <div class="card my-5 col-lg-6 offset-lg-3">
    <div class="card-body">
      <form method="post" action="{% url 'register:password_reset' %}" >
        {% csrf_token %}
        <div class="form-group">
          {{form.email.label_tag}}
          {{form.email}}
        </div>
        <input type="submit" class="btn btn-primary float-right" value="パスワードをリセット" />
        <input type="hidden" name="next" value="{{ next }}" />
      </form>
    </div>
  </div>
</div>

{% endblock %}

register/templates/register/password_reset_complete.html
{% extends "appbase.html" %}

{% block title %}
パスワードのリセット
{% endblock %}

{% block content %}
<div class="row">
  <div class="card my-5 col-lg-6 offset-lg-3">
    <div class="card-body">
      新しいパスワードが設定されました。
    </div>
  </div>
</div>

{% endblock %}

register/templates/register/password_reset_confirm.html
{% extends "appbase.html" %}

{% block title %}
  パスワードのリセット
{% endblock %}

{% block content %}
<div class="row">
  <div class="card my-5 col-lg-6 offset-lg-3">
    <div class="card-body">
      {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {% for _, err_state in form.errors.items %}
            {{err_state}}
          {% endfor %}
        </div>
      {% endif %}

      <div class="my-2">
        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            {{form.new_password1.label_tag}}
            {{form.new_password1}}
          </div>
          <div class="form-group">
            {{form.new_password2.label_tag}}
            {{form.new_password2}}
          </div>
          <input type="submit" class="btn btn-primary float-right my-2" value="変更" />
          <input type="hidden" name="next" value="{{ next }}" />
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

register/templates/register/password_reset_done.html
{% extends "appbase.html" %}

{% block title %}
パスワードのリセット
{% endblock %}

{% block content %}
<div class="row">
  <div class="card my-5 col-lg-6 offset-lg-3">
    <div class="card-body">
      パスワードのリセットを行うためのURLを送信しました。
    </div>
  </div>
</div>

{% endblock %}

register/templates/register/password_reset_email.html
{{user.username}} さま

UTAKO TUNE( {{protocol}}://{{domain}}/ )にてパスワードのリセットが要求されました。

これがあなたの行った操作である場合、 {{protocol}}://{{domain}}{% url 'register:password_reset_confirm' uidb64=uid token=token %} からリセットしてください。
そうではない場合、無視していただいて構いません。

今後ともUTAKO TUNEをよろしくお願いいたします。

register/templates/register/password_reset_email_old.html
{{user.name}} さま

UTAKO TUNE( {{protocol}}://{{domain}}/ )にてパスワードのリセットが要求されました。

これがあなたの行った操作である場合、 {{protocol}}://{{domain}}{% url 'password_reset_confirm' uidb64=uid token=token %} からリセットしてください。
そうではない場合、無視していただいて構いません。

今後ともUTAKO TUNEをよろしくお願いいたします。

register/templates/register/password_reset_subject.html
パスワードのリセット | UTAKO TUNE

register/templates/register/register.html
{% extends "appbase.html" %}

{% block title %}
  新規登録
{% endblock %}

{% block content %}
<div class="row">
  <div class="card my-5 col-lg-6 offset-lg-3">
    <div class="card-body">
      {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {% for _, err_state in form.errors.items %}
            {{err_state}}
          {% endfor %}
        </div>
      {% endif %}

      <div class="my-2">
        <form method="post" action="{% url 'register:register' %}">
          {% csrf_token %}
          <div class="form-group">
            {{form.username.label_tag}}
            {{form.username}}
          </div>
          <div class="form-group">
            {{form.email.label_tag}}
            {{form.email}}
          </div>
          <div class="form-group">
            {{form.password1.label_tag}}
            {{form.password1}}
          </div>
          <div class="form-group">
            {{form.password2.label_tag}}
            {{form.password2}}
          </div>
          <input type="submit" class="btn btn-primary float-right my-2" value="登録" />
          <input type="hidden" name="next" value="{{ next }}" />
        </form>
      </div>
      <a href="{% url "social:begin" "google-oauth2" %}"><div class="btn btn-primary col-12 my-2">Googleでログイン</div></a>
      <a href="{% url "social:begin" "twitter" %}"><div class="btn btn-primary col-12 my-2">Twitterでログイン</div></a>
    </div>
  </div>
</div>

{% endblock %}