UtakoSite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.flatpages import views
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movie.urls')),
    path('auth/', include('register.urls')),
    path('mypage/', include('mypage.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('player/', views.flatpage, {'url': 'player/'}),
    re_path('^$', views.flatpage, {'url': 'index/'}),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path('^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

api/urls.py
from django.urls import path, include
from rest_framework import routers, serializers, viewsets
from .views import StatusList, StatusRetrieve, MapRangeList, MapPointList, PlayerList, SettingsRetrieve
from rest_framework import routers

urlpatterns = [
    path('movie/', StatusList.as_view()),
    path('movie/<str:pk>/', StatusRetrieve.as_view(), name='detail'),
    path('vocalosphere/range/', MapRangeList.as_view()),
    path('vocalosphere/point/', MapPointList.as_view()),
    path('player/', PlayerList.as_view()),
    path('settings/', SettingsRetrieve.as_view()),
]

movie/models/song_index.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from .status import Status

class SongIndex(models.Model):
    id = models.AutoField(primary_key=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE, max_length=12, default="UNKNOWN")  # Field name made lowercase.
    value0 = models.FloatField()
    value1 = models.FloatField()
    value2 = models.FloatField()
    value3 = models.FloatField()
    value4 = models.FloatField()
    value5 = models.FloatField()
    value6 = models.FloatField()
    value7 = models.FloatField()
    version = models.IntegerField()

    @property
    def values(self):
        return [ getattr(self, "value{}".format(i)) for i in range(8)]

    class Meta:
        db_table = 'song_index'
        unique_together = (('status', 'version'),)
        indexes = [
            models.Index(fields=['value0',]),
            models.Index(fields=['value1',]),
            models.Index(fields=['value2',]),
            models.Index(fields=['value3',]),
            models.Index(fields=['value4',]),
            models.Index(fields=['value5',]),
            models.Index(fields=['value6',]),
            models.Index(fields=['value7',]),
        ]

UtakoSite/templates/ads.html
<p class="text-secondary text-center">スポンサーリンク</p>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
style="display:block; text-align:center;"
data-ad-layout="in-article"
data-ad-format="fluid"
data-ad-client="{{ google_ad_client }}"
data-ad-slot="7060731324"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

UtakoSite/templates/appbase.html
{% extends "base.html" %}

{% block body %}
<div class="container">
{% block content %}
{% endblock %}
</div>
{% endblock %}

UtakoSite/templates/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ google_analytics }}"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', "{{ google_analytics }}");
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="人工知能を用いてニコニコ動画上のVOCALOID曲を解析し，
    あなたの好きな曲から新しい曲をおすすめします．現在パブリックβテスト中．">
    {% if request.get_full_path != "/" %}
    <meta name="robots" content="noindex,noarchive">
    {% endif %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="{% static 'startbootstrap-landing-page/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'startbootstrap-landing-page/vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    {% block extra_css %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="icon" type="image/x-icon" href="
    {% if isdebug %}
    {% static 'favicon_edge.ico' %}
    {% else %}
    {% static 'favicon.ico' %}
    {% endif %}
    ">
    <title>{% block title %}{% endblock %} | UTAKO TUNE</title>
  </head>
  <body>
    <div class="pos-f-t">
      <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <a href="/" class="navbar-brand"><img src={% static 'img/long_logo.svg' %}></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <div class="navbar-nav">
            <a href="/movie/" class='nav-item nav-link'>Search</a>
            <a href="/player/" class='nav-item nav-link'>Player</a>
            <a href="#" class='nav-item nav-link disabled'>VOCALOSPHERE</a>
            {% if user.is_authenticated %}
              <a href="/mypage/" class='nav-item nav-link'>UserPage</a>
              <a href="/auth/logout/" class='nav-item nav-link'>SignOut</a>
            {% else %}
              <a href="/auth/login/" class='nav-item nav-link'>SignIn</a>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    {% block body %}
    {{ content }}
    {% endblock %}
    <!-- Footer -->
    <footer>
      <div class="container text-center">
        <p>Copyright &copy; Nanamachi 2018</p>
        <p>サイト内で紹介されている動画の権利は各投稿者に帰属します</p>
      </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block extra_js %}{% endblock %}
  </body>
</html>

UtakoSite/templates/movie_card.html
{% load static %}
<div class='col-lg-3 col-md-4 col-6 my-3'>
  <a href="/movie/{{card.movie.id}}">
  <div class="card">
    <img class="card-img-top" src="
    {% if card.thumbnail_url %}
      {{card.thumbnail_url}}
    {% else %}
      {% static "img/thumbnail_not_found.png" %}
    {% endif %}
    ">
    <div class="card-body text-secondary">
      <p>{{card.title}}</p>
      <table class="table table-sm">
        <tbody>
          <tr>
            <th><i class="icon-clock"></i></th>
            <td>{{card.first_retrieve}}</td>
          </tr><tr>
            <th><i class="icon-user"></i></th>
            <td>{{card.user_nickname}}</td>
          </tr><tr>
            <th><i class="icon-graph"></i></th>
            <td>{{card.movie.score | floatformat:2}}</td>
          </tr><tr>
            <th><i class="icon-eye"></i></th>
            <td>{{card.view_counter}}</td>
          </tr><tr>
            <th><i class="icon-bubble"></i></th>
            <td>{{card.comment_num}}</td>
          </tr><tr>
            <th><i class="icon-star"></i></th>
            <td>{{card.mylist_counter}}</td>
          </tr><tr>
            <th><i class="icon-energy"></i></th>
            <td>
              {% if card.movie.songindex_set.count > 0 %}
              <span class="text-success">解析済</span>
              {% else %}
              <span class="text-secondary">未解析</span>
              {% endif %}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  </a>
</div>

UtakoSite/templates/paginator.html
{% load page_with_query %}

<div class="m-3">
<ul class="pagination">
{% if page_obj.has_previous %}
  <li class="page-item">
    <a href="?{% page_with_query request 1 %}" class="page-link">&laquo; First</a>
  </li>
  <li class="page-item" class="page-link">
    <a href="?{% page_with_query request page_obj.previous_page_number %}" class="page-link">Previous</a>
  </li>
{% endif %}
<li class="page-item active">
  <span class="page-link">{{ page_obj.number }}</span>
</li>
{% if page_obj.has_next %}
  <li class="page-item">
    <a href="?{% page_with_query request page_obj.next_page_number %}" class="page-link">Next</a>
  </li>
{% endif %}
</ul>
</div>

UtakoSite/templates/searchbox.html
<div class="m-3">
  <form action='/movie/' method='get'>
    <div class="form-group">
      <input class="form-control" name="q" value="{% if nico_api.q %}{{ nico_api.q }}{% endif %}" placeholder="検索ワード">
    </div>
    <div class='form-row'>
      <div class="form-group col-md-3 offset-md-3 custom-control custom-checkbox">
        <input
        type="checkbox"
        class="custom-control-input"
        id="not_analyzed"
        name="not_analyzed"
        style="position: static"
        {% if not_analyzed is True %}
          checked
        {% endif %} >
        <label class="custom-control-label" for="not_analyzed">解析されていない動画も表示する</label>
      </div>
      <div class="form-group col-md-4">
        <select class="form-control" name="sortby">
          <option value="-postdate"
            {% if sortby == "-postdate" %} selected {% endif %}
          >新着順</option>
          <option value="postdate"
            {% if sortby == "postdate" %} selected {% endif %}
          >古い順</option>
          <option value="-score"
            {% if sortby == "-score" %} selected {% endif %}
          >再生スコア順</option>
          <option value="score"
            {% if sortby == "score" %} selected {% endif %}
          >再生スコア逆順</option>
        </select>
      </div>
      <div class="form-group col-md-2">
        <button type="submit" class="btn btn-primary">検索</button>
      </div>
    </div>
  </form>
</div>